kubectl apply -f namespace/
kubectl apply -f secrets/
kubectl apply -f configmap/
kubectl apply -f services/
kubectl apply -f deployments/
kubectl apply -f statefulsets/validator1.yaml
kubectl apply -f statefulsets/validator2.yaml
kubectl apply -f statefulsets/validator3.yaml
kubectl apply -f statefulsets/validator4.yaml