apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-config-toml-configmap
  labels:
    app: besu-config-toml-configmap
  namespace: besu
data:
  nodes.json: |-
    [
      "enode://c1979a8a48693db804316b5acebe35e11731e1fb1c9c21ff7268ab25db6f6e03390a429b83cf0ec0865a7205f2669ec1ace652a3def11e2e01571c74939cbe22@validator1-0.besu-validator1.besu.svc.cluster.local:30303",
      "enode://e40129f02c9e29a02049668346d4777bb55809042746882b33b20a8b5a7310eb5f107a53f0aa3da766ee77f401557a79c0c328329ea48bf0996c6c9dff817f76@validator2-0.besu-validator2.besu.svc.cluster.local:30303",
      "enode://a3e4af081a0ab853c959b9acd0596f818b91a9409b9d04c50af055072c929abfa340e14111dcfa76e049fdb16bb9198e722d5e7be3e8ef37562ea0d0ce1eda11@validator3-0.besu-validator3.besu.svc.cluster.local:30303",
      "enode://8f4e444a73034236ab4244c7a572aa2c6198b9e0d483ef17bf4b751cac5c0370bc527a5b0c5d01aa3ef41704af838c74730aeecac0f0c22dc4c17b0a9f03ad76@validator4-0.besu-validator4.besu.svc.cluster.local:30303"
    ]
  
  config.toml: |-
    data-path="/data"
    genesis-file="/etc/genesis/genesis.json"
    static-nodes-file="/etc/besu/static-nodes.json"
    min-gas-price=0
    p2p-enabled=true
    discovery-enabled=true
    p2p-port=30303
    max-peers=25
    host-allowlist=["*"]
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "WEB3"]
    rpc-http-cors-origins=["*"]
    rpc-http-authentication-enabled=false
    graphql-http-enabled=false
    graphql-http-host="0.0.0.0"
    graphql-http-port=8547
    graphql-http-cors-origins=["*"]
    rpc-ws-enabled=false
    rpc-ws-host="0.0.0.0"
    rpc-ws-port=8546
    rpc-ws-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "EEA", "WEB3"]
    rpc-ws-authentication-enabled=false


